### ISSUE TITLE
Write mocks for testing the AJAX Api

### ISSUE THREAD

**Issue by MykalMachon** [TinyboxSoftware/smolcart.js#4]
## Summary
I need to create some mocks of the [Shopify Ajax Cart API](https://shopify.dev/docs/themes/ajax-api/reference/cart) so we can properly test the library and ensure it's interacting properly with the library. 

After these mocks are complete we can create comprehensive tests for the library. 

## Todos
- [x] Mock the `POST /cart/add.js` route 
- [x] Mock the `GET /cart.js` route
- [x] Mock the `POST /cart/update.js` route
- [x] Mock the `POST /cart/change.js` route 
- [x] Mock the `POST /cart/clear.js` route

**Comment by MykalMachon** [comment]
Awaiting merge of #6 to mark this issue as complete

**Comment by MykalMachon** [comment]
was completed by #6
